package edu.osu.synergies.simple.model1;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import org.ascape.util.vis.DrawFeature;

import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

/**
 * <!-- begin-user-doc -->
 * Lot Style 2D Java Implementation.
 * 
 * Generated by AMF for model: SpatialResources.metaabm in project: edu.osu.synergies.ascape 
 * <!-- end-user-doc -->
 * @generated
 */
public class LotStyle2D extends DrawFeature {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void draw(Graphics g, Object object, int width, int height) {
		Shape shape = null;
		Lot actions = (Lot) object;
		Lot defaultSpatialResourcesAgentStyle = actions;
		java.awt.Color defaultSpatialResourcesAgentColor = new java.awt.Color(
				(float) .94, (float) 1.0, (float) .93)

		;

		g.setColor(defaultSpatialResourcesAgentColor);
		shape = new Rectangle2D.Double(0, 0, width, height);
		((Graphics2D) g).fill(shape);
	}
}
