package edu.osu.synergies.spatial;

import org.eclipse.draw2d.ColorConstants;
import org.eclipse.draw2d.Graphics;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.widgets.Display;

import org.ascape.model.Agent;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

import org.ascape.util.vis.DrawFeature;

/**
 * <!-- begin-user-doc -->
 * Lot Style 2D Java Implementation.
 * 
 * Generated by AMF for model: SpatialResources.metaabm in project: edu.osu.synergies 
 * <!-- end-user-doc -->
 * @generated
 */
public class LotStyle2DGraphics extends DrawFeature {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	enum Shapes {
		rectangle, oval, marker
	};

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	Shapes shape = Shapes.rectangle;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void draw(Graphics g, Object object, int width, int height) {

		Lot actions = (Lot) object;
		Lot defaultSpatialResourcesAgentStyle = actions;
		if (defaultSpatialResourcesAgentStyle.getSpatialResources()
				.isWandering()) {
			Color defaultSpatialResourcesAgentColor = new Color(
					Display.getCurrent(), (int) (0.9 * 255), (int) (0.9 * 255),
					(int) (0.9 * 255));

			g.setForegroundColor(defaultSpatialResourcesAgentColor);
			g.setBackgroundColor(defaultSpatialResourcesAgentColor);
			shape = shape.rectangle;
			if (shape == Shapes.oval) {
				g.fillOval(0, 0, width, height);
			} else if (shape == Shapes.marker) {
				int d = (int) (width * .25 - 1);
				int d2 = (int) (width * .5 - 1);
				g.fillOval(d, d, d2, d2);
			} else if (shape == Shapes.rectangle) {
				g.fillRectangle(0, 0, width, height);
			}
		}
		if (!defaultSpatialResourcesAgentStyle.getSpatialResources()
				.isWandering()) {
			Color colorRGB_Literal0pt8Literal0pt8Literal0pt8_ = new Color(
					Display.getCurrent(), (int) (0.8 * 255), (int) (0.8 * 255),
					(int) (0.8 * 255));

			g.setForegroundColor(colorRGB_Literal0pt8Literal0pt8Literal0pt8_);
			g.setBackgroundColor(colorRGB_Literal0pt8Literal0pt8Literal0pt8_);
			shape = shape.rectangle;
			if (shape == Shapes.oval) {
				g.fillOval(0, 0, width, height);
			} else if (shape == Shapes.marker) {
				int d = (int) (width * .25 - 1);
				int d2 = (int) (width * .5 - 1);
				g.fillOval(d, d, d2, d2);
			} else if (shape == Shapes.rectangle) {
				g.fillRectangle(0, 0, width, height);
			}
		}
	}
}
