package edu.osu.synergies.spatial;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import org.ascape.util.vis.DrawFeature;

import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

/**
 * <!-- begin-user-doc -->
 * Learner Style 2D Java Implementation.
 * 
 * Generated by AMF for model: SpatialResources.metaabm in project: edu.osu.synergies.ascape 
 * <!-- end-user-doc -->
 * @generated
 */
public class LearnerStyle2D extends DrawFeature {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void draw(Graphics g, Object object, int width, int height) {
		Shape shape = null;
		HostCell actionsCell = (HostCell) object;
		if (actionsCell.getOccupant() instanceof Learner) {
			Learner actions = (Learner) actionsCell.getOccupant();
			Learner defaultSimpleResourcesAgentStyle = actions;
			double learnerIndexDivideLearnerCount = //div
			defaultSimpleResourcesAgentStyle.getLearnerIndex()
					/ defaultSimpleResourcesAgentStyle.getSpatialResources()
							.getLearnerCount();

			java.awt.Color defaultSimpleResourcesAgentColor = //colorRGB
			new java.awt.Color((float) 0.5, (float) 0.6,
					(float) learnerIndexDivideLearnerCount)

			;

			g.setColor(defaultSimpleResourcesAgentColor);
			shape = new Ellipse2D.Double(0, 0, width - 2, height - 2);
			((Graphics2D) g).fill(shape);
		}
	}
}
