package edu.osu.synergies.spatial;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Rectangle2D;
import org.ascape.util.vis.DrawFeature;

import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;

/**
 * <!-- begin-user-doc -->
 * Lot Style 2D Java Implementation.
 * 
 * Generated by AMF for model: SpatialResources.metaabm in project: edu.osu.synergies.ascape 
 * <!-- end-user-doc -->
 * @generated
 */
public class LotStyle2D extends DrawFeature {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void draw(Graphics g, Object object, int width, int height) {
		Shape shape = null;
		Lot actions = (Lot) object;
		Lot defaultSpatialResourcesAgentStyle = actions;
		if (defaultSpatialResourcesAgentStyle.getSpatialResources()
				.isWandering()) {
			java.awt.Color defaultSpatialResourcesAgentColor = //colorRGB
			new java.awt.Color((float) 0.9, (float) 0.9, (float) 0.9)

			;

			g.setColor(defaultSpatialResourcesAgentColor);
			shape = new Rectangle2D.Double(0, 0, width, height);
			((Graphics2D) g).fill(shape);
		}
		if (!defaultSpatialResourcesAgentStyle.getSpatialResources()
				.isWandering()) {
			java.awt.Color colorRGB_Literal0pt8Literal0pt8Literal0pt8_ = //colorRGB
			new java.awt.Color((float) 0.8, (float) 0.8, (float) 0.8)

			;

			g.setColor(colorRGB_Literal0pt8Literal0pt8Literal0pt8_);
			shape = new Rectangle2D.Double(0, 0, width, height);
			((Graphics2D) g).fill(shape);
		}
	}
}
