package edu.osu.synergies.simple.model2;

import org.eclipse.amp.agf.IGraphicsAdapter;
import org.eclipse.jface.viewers.IColorProvider;
import org.eclipse.jface.viewers.ILabelProvider;

import edu.osu.synergies.simple.model1.LearnerCustomColorProvider;

/**
 * <!-- begin-user-doc -->
 * SimpleResources Java Implementation.
 * 
 * Generated by AMF for model: SpatialResources.metaabm in project: edu.osu.synergies 
 * <!-- end-user-doc -->
 * @generated
 */
public class SocialResourcesCustomGraphicsAdapter extends SocialResourcesGraphicsAdapter {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static IGraphicsAdapter singleton;

	IColorProvider[] learnerColorProviders = new IColorProvider[]{LearnerCustomColorProvider
			.getDefault()};

	IColorProvider[] guideColorProviders = new IColorProvider[]{GuideCustomColorProvider
			.getDefault()};
	
	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getColorsForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IColorProvider[] getColorsForClass(Class type) {
		if (type == Learner.class) {
			return learnerColorProviders;
		}
		return super.getColorsForClass(type);
	}


	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getLabelsForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ILabelProvider[] getLabelsForClass(Class type) {
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static IGraphicsAdapter getDefault() {
		if (singleton == null) {
			singleton = new SocialResourcesCustomGraphicsAdapter();
		}
		return singleton;
	}
}
