package edu.osu.synergies.simple.model1;

import java.util.ArrayList;
import java.util.List;
import java.util.Collections;

import org.eclipse.core.runtime.IAdapterFactory;
import org.eclipse.amp.agf.IGraphicsAdapted;
import org.eclipse.amp.agf.IGraphicsAdapter;

import org.eclipse.swt.graphics.Color;
import org.eclipse.jface.viewers.IColorProvider;

import org.ascape.model.Agent;
import org.ascape.model.Cell;
import org.ascape.model.CellOccupant;
import org.ascape.model.HostCell;
import org.ascape.model.LocatedAgent;
import org.ascape.model.Scape;
import org.ascape.model.event.ScapeEvent;
import org.ascape.model.rule.Rule;
import org.ascape.model.rule.ExecuteThenUpdate;
import org.ascape.model.space.CollectionSpace;
import org.ascape.model.space.Coordinate;
import org.ascape.model.space.Coordinate2DDiscrete;
import org.ascape.model.space.Graph;
import org.ascape.model.space.Location;
import org.ascape.model.space.Singleton;
import org.ascape.runtime.NonGraphicRunner;
import org.ascape.util.Conditional;
import org.ascape.util.data.DataPoint;
import org.ascape.util.data.DataPointConcrete;
import org.ascape.util.vis.ColorFeature;
import org.ascape.util.vis.ColorFeatureConcrete;
import org.ascape.view.vis.ChartView;
import org.ascape.view.vis.GEFView;
import org.ascape.view.vis.GraphView;

import org.eclipse.amp.escape.runtime.extension.IAgentChild;
import org.eclipse.amp.escape.runtime.extension.IAgentChildProvider;

/**
 * <!-- begin-user-doc -->
 * Learning Resource Java Implementation.
 * 
 * Generated by AMF for model: SpatialResources.metaabm in project: edu.osu.synergies 
 * <!-- end-user-doc -->
 * @generated
 */
public class LearningResource extends CellOccupant
		implements
			IAgentChildProvider {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private double efficacy = 0.0;
	/**
	 * <!-- begin-user-doc -->
	 * A unique identifier for the resource.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private int resourceID = 0;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private List<IAgentChild> children;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public List<IAgentChild> getChildren() {
		return children;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Constructs a new Learning Resource.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public LearningResource() {

		children = new ArrayList<IAgentChild>();

	}
	//todo, make this a useful value for evaluating compatibility of different versions of generated classes

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static final long serialVersionUID = 89989998L;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static long nextUniqueID;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private long uniqueID;

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public long getUID() {
		if (uniqueID == 0) {
			uniqueID = nextUniqueID++;
		}
		return uniqueID;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Clones the agent, ensuring that a unique id is assigned.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object clone() {
		try {
			LearningResource clone = (LearningResource) super.clone();
			clone.uniqueID = 0;
			return clone;
		} catch (Exception e) {
			throw new RuntimeException("Unexpected cloning exception: " + e);
		}
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SpatialResources getSpatialResources() {
		return (SpatialResources) getScape().getScape();
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */

	public void startSimulationAgentChild(int timeStep) {
		if (timeStep == getRoot().getRunner().getEarliestPeriod()) {
			for (IAgentChild tmp : children) {
				tmp.startSimulation(timeStep);
			}
		}
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */

	public void calculateTimeStep(int timeStep) {
		for (IAgentChild tmp : children) {
			tmp.calculate(timeStep);
		}
	}

	/**
	 * <!-- begin-user-doc -->
	 * Initialize Location Initialization. Executed once at the beginning of each model run.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void initializeLocation() {
		final Object learningResource = (Object) ((org.ascape.model.space.Discrete) getSpatialResources()
				.getDistrict().getSpace()).findRandomAvailable();
		if (learningResource != null) {
			if (getHostScape() != ((Agent) learningResource).getScape()) {
				die();
				getSpatialResources().getLearningResourceScape().add(this);
			}
			moveTo(((HostCell) learningResource));
		}
	}
	/**
	 * <!-- begin-user-doc -->
	 * Initialize State Initialization. Executed once at the beginning of each model run.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void initializeState() {
		double resourceEfficacy = resourceEfficacy();
		setEfficacy(resourceEfficacy);
	}
	/**
	 * <!-- begin-user-doc -->
	 * Calculate Resource Efficacy.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public double resourceEfficacy() {
		double resourceEfficacyMinimum = getSpatialResources()
				.getResourceEfficacyMinimum();
		double resourceEfficacyMaximum = getSpatialResources()
				.getResourceEfficacyMaximum();
		return randomInRange(resourceEfficacyMinimum, resourceEfficacyMaximum);
	}
	/**
	 * <!-- begin-user-doc -->
	 * Initialize ID Initialization. Executed once at the beginning of each model run.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void initializeID() {
		setResourceID(getSpatialResources().getNextResourceID());
		int incrementResourceID = getResourceID() + 1;
		getSpatialResources().setNextResourceID(incrementResourceID);
	}
	/**
	 * <!-- begin-user-doc -->
	 * Gets the Efficacy property for Learning Resource.
	 * @return 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public double getEfficacy() {
		return efficacy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Efficacy property for Learning Resource.
	 * 
	 * @param _efficacy the new Efficacy value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setEfficacy(double _efficacy) {
		efficacy = _efficacy;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Gets the Resource ID property for Learning Resource.
	 * @return A unique identifier for the resource.
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public int getResourceID() {
		return resourceID;
	}

	/**
	 * <!-- begin-user-doc -->
	 * Sets the Resource ID property for Learning Resource.
	 * A unique identifier for the resource.
	 * @param _resourceID the new Resource ID value
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setResourceID(int _resourceID) {
		resourceID = _resourceID;
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public String getName() {
		if (name == null) {
			return "Learning Resource " + getUID();
		} else {
			return name;
		}
	}
}
