package edu.osu.synergies.simple.model1;

import org.eclipse.amp.agf.IGraphicsAdapter;
import org.eclipse.amp.agf.GraphicsAdapter;
import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.core.runtime.IAdapterFactory;

import org.eclipse.amp.agf.gef.IFigureProvider;
import org.eclipse.jface.viewers.IColorProvider;
import org.eclipse.jface.viewers.ILabelProvider;

/**
 * <!-- begin-user-doc -->
 * SimpleResources Java Implementation.
 * 
 * Generated by AMF for model: SpatialResources.metaabm in project: edu.osu.synergies 
 * <!-- end-user-doc -->
 * @generated
 */
public class SimpleResourcesGraphicsAdapter extends GraphicsAdapter {

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	private static IGraphicsAdapter singleton;

	IColorProvider[] simpleResourcesColorProviders = new IColorProvider[]{};
	IColorProvider[] learnerColorProviders = new IColorProvider[]{LearnerStyle2DColorProvider
			.getDefault()};
	IColorProvider[] learningResourceColorProviders = new IColorProvider[]{LearningResourceStyle2DColorProvider
			.getDefault()};
	IColorProvider[] resourceInteractionColorProviders = new IColorProvider[]{ResourceInteractionStyle2DColorProvider
			.getDefault()};
	IColorProvider[] homeColorProviders = new IColorProvider[]{HomeStyle2DColorProvider
			.getDefault()};

	IFigureProvider[] simpleResourcesFigureProviders = new IFigureProvider[]{};
	IFigureProvider[] learnerFigureProviders = new IFigureProvider[]{LearnerStyle2DFigureProvider
			.getDefault()};
	IFigureProvider[] learningResourceFigureProviders = new IFigureProvider[]{LearningResourceStyle2DFigureProvider
			.getDefault()};
	IFigureProvider[] resourceInteractionFigureProviders = new IFigureProvider[]{ResourceInteractionStyle2DFigureProvider
			.getDefault()};
	IFigureProvider[] homeFigureProviders = new IFigureProvider[]{HomeStyle2DFigureProvider
			.getDefault()};

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getColorsForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IColorProvider[] getColorsForClass(Class type) {
		if (type == SimpleResources.class) {
			return simpleResourcesColorProviders;
		}
		if (type == Learner.class) {
			return learnerColorProviders;
		}
		if (type == LearningResource.class) {
			return learningResourceColorProviders;
		}
		if (type == ResourceInteraction.class) {
			return resourceInteractionColorProviders;
		}
		if (type == Home.class) {
			return homeColorProviders;
		}
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getFiguresForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public IFigureProvider[] getFiguresForClass(Class type) {
		if (type == SimpleResources.class) {
			return simpleResourcesFigureProviders;
		}
		if (type == Learner.class) {
			return learnerFigureProviders;
		}
		if (type == LearningResource.class) {
			return learningResourceFigureProviders;
		}
		if (type == ResourceInteraction.class) {
			return resourceInteractionFigureProviders;
		}
		if (type == Home.class) {
			return homeFigureProviders;
		}
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * @param type
	 * @return
	 * @see org.eclipse.amp.agf.IGraphicsAdapter#getLabelsForClass(java.lang.Class)
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ILabelProvider[] getLabelsForClass(Class type) {
		return null;
	}

	/**
	 * <!-- begin-user-doc -->
	 * 
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static IGraphicsAdapter getDefault() {
		if (singleton == null) {
			singleton = new SimpleResourcesGraphicsAdapter();
		}
		return singleton;
	}
}
